---
title: "Model Selection for Environmental Parameters in SGD that may affect Physiological Rates"
author: "Hannah Merges"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning=FALSE, 
                      message=FALSE)
```

## Loading libraries 
```{r, echo=FALSE}
library(LoLinR)
library(lubridate)
library(patchwork)
library(tidyverse)
library(here)
library(car)
library(GGally)
library(corrplot)
library(PNWColors)
library(seacarb)
library(broom)
library(agricolae)
library(lme4)
library(lmerTest)
library(modelsummary)
library(performance)
library(emmeans)
library(MuMIn)
```

## Loading Data
```{r}
RespoR_Normalized_Full_ExcelUpdates <- read_csv(here::here("Data","RespoFiles", "Respo_RNormalized_AllRates.csv"))
NEC_wnuts <- read_csv(here("Data", "NEC_wnuts_edit.csv"))
FULL_RespoNEC_allParams <- read_csv(here("Data", "RespoR_Normalized_Full4_withNEC.csv"))
```

## Tidy the data in a way that will be useful for model selection 
separate by site (V/C) and by physio measurement (NP/R/GP) and a separate df for NEC 

```{r}
FULL_RespoNEC_allParams <- FULL_RespoNEC_allParams %>% 
  select(!c("pH","light_dark", "umol.cm2.hr_uncorr", "TrisCalDate":"temp_C")) %>% 
  mutate(Salinity=salinity)

FULL_RespoNEC_allParams$phosphate_umolL <- as.numeric(FULL_RespoNEC_allParams$phosphate_umolL)
FULL_RespoNEC_allParams$silicate_umolL <- as.numeric(FULL_RespoNEC_allParams$silicate_umolL)
FULL_RespoNEC_allParams$NN_umolL <- as.numeric(FULL_RespoNEC_allParams$NN_umolL)
FULL_RespoNEC_allParams$ammonia_umolL <- as.numeric(FULL_RespoNEC_allParams$ammonia_umolL)
FULL_RespoNEC_allParams$salinity <- as.numeric(FULL_RespoNEC_allParams$salinity)
FULL_RespoNEC_allParams$new_pH <- as.numeric(FULL_RespoNEC_allParams$new_pH)
FULL_RespoNEC_allParams$TA_initial <- as.numeric(FULL_RespoNEC_allParams$TA_initial)

RespoR_Normalized_Full_ExcelUpdates_V_NP <- FULL_RespoNEC_allParams %>% 
  filter(site=="Varari", 
         P_R=="NP") %>% 
  pivot_longer(cols = phosphate_umolL:Salinity, names_to = "Predictor_Variable", values_to = "Predictor_Values") %>% 
  mutate(Response_Variable=umol.cm2.hr) %>% 
  drop_na(umol.cm2.hr) %>% 
  filter(!is.infinite(umol.cm2.hr))

RespoR_Normalized_Full_ExcelUpdates_V_GP <- FULL_RespoNEC_allParams %>% 
  filter(site=="Varari", 
         P_R=="GP") %>% 
  pivot_longer(cols = phosphate_umolL:Salinity, names_to = "Predictor_Variable", values_to = "Predictor_Values") %>% 
  mutate(Response_Variable=umol.cm2.hr) %>% 
  drop_na(umol.cm2.hr) %>% 
  filter(!is.infinite(umol.cm2.hr))

RespoR_Normalized_Full_ExcelUpdates_V_R <- FULL_RespoNEC_allParams %>% 
   filter(site=="Varari", 
         P_R=="R") %>% 
  pivot_longer(cols = phosphate_umolL:Salinity, names_to = "Predictor_Variable", values_to = "Predictor_Values") %>% 
  mutate(Response_Variable=umol.cm2.hr) %>% 
  drop_na(umol.cm2.hr) %>% 
  filter(!is.infinite(umol.cm2.hr))

RespoR_Normalized_Full_ExcelUpdates_C_NP <- FULL_RespoNEC_allParams %>% 
  filter(site=="Cabral", 
         P_R=="NP") %>% 
  pivot_longer(cols = phosphate_umolL:Salinity, names_to = "Predictor_Variable", values_to = "Predictor_Values") %>% 
  mutate(Response_Variable=umol.cm2.hr) %>% 
  drop_na(umol.cm2.hr) %>% 
  filter(!is.infinite(umol.cm2.hr)) %>% 
  drop_na(Predictor_Values)

RespoR_Normalized_Full_ExcelUpdates_C_GP <- FULL_RespoNEC_allParams %>% 
  filter(site=="Cabral", 
         P_R=="GP") %>% 
  pivot_longer(cols = phosphate_umolL:Salinity, names_to = "Predictor_Variable", values_to = "Predictor_Values") %>% 
  mutate(Response_Variable=umol.cm2.hr) %>% 
  drop_na(umol.cm2.hr) %>% 
  filter(!is.infinite(umol.cm2.hr)) %>% 
  drop_na(Predictor_Values)

RespoR_Normalized_Full_ExcelUpdates_C_R <- FULL_RespoNEC_allParams %>% 
  filter(site=="Cabral", 
         P_R=="R") %>% 
  pivot_longer(cols = phosphate_umolL:Salinity, names_to = "Predictor_Variable", values_to = "Predictor_Values") %>% 
  mutate(Response_Variable=umol.cm2.hr) %>% 
  drop_na(umol.cm2.hr) %>% 
  filter(!is.infinite(umol.cm2.hr)) %>% 
  drop_na(Predictor_Values)


```

## try making nonlienar models for each of these 

```{r}
## for Varari NP 
MS_V_NP_nonlinear <- RespoR_Normalized_Full_ExcelUpdates_V_NP %>%
  nest(data = -c(Predictor_Variable)) %>% # nest all the data measurement type
  mutate(fit = map(data, ~lm(Response_Variable~ poly(Predictor_Values, degree=2), data = .))) #create models
MS_V_NP_nonlinear

MS_V_NP_nonlinear_fit <- MS_V_NP_nonlinear$fit # shows you each of the models

MS_V_NP_nonlinear_fitresults <- MS_V_NP_nonlinear %>%
  mutate(coeff = map(fit, tidy),
         aic =  map(fit, glance)) %>% # R2 and others
  select(Predictor_Variable, coeff, aic) %>% # only keep the results
  unnest() %>%
  write_csv(here::here("Outputs", "ModelSelection", "V_NP.csv"))

## for Varari GP
MS_V_GP_nonlinear <- RespoR_Normalized_Full_ExcelUpdates_V_GP %>%
  nest(data = -c(Predictor_Variable)) %>% # nest all the data measurement type
  mutate(fit = map(data, ~lm(Response_Variable~ poly(Predictor_Values, degree=2), data = .))) #create models
MS_V_GP_nonlinear

MS_V_GP_nonlinear_fit <- MS_V_GP_nonlinear$fit # shows you each of the models

MS_V_GP_nonlinear_fitresults <- MS_V_GP_nonlinear %>%
  mutate(coeff = map(fit, tidy),
         aic =  map(fit, glance)) %>% # R2 and others
  select(Predictor_Variable, coeff, aic) %>% # only keep the results
  unnest() %>%
  write_csv(here::here("Outputs", "ModelSelection", "V_GP.csv"))

## for Varari R
MS_V_R_nonlinear <- RespoR_Normalized_Full_ExcelUpdates_V_R %>%
  nest(data = -c(Predictor_Variable)) %>% # nest all the data measurement type
  mutate(fit = map(data, ~lm(Response_Variable~ poly(Predictor_Values, degree=2), data = .))) #create models
MS_V_R_nonlinear

MS_V_R_nonlinear_fit <- MS_V_R_nonlinear$fit # shows you each of the models

MS_V_R_nonlinear_fitresults <- MS_V_R_nonlinear %>%
  mutate(coeff = map(fit, tidy),
         aic =  map(fit, glance)) %>% # R2 and others
  select(Predictor_Variable, coeff, aic) %>% # only keep the results
  unnest() %>%
  write_csv(here::here("Outputs", "ModelSelection", "V_R.csv"))

## for Cabral R
MS_C_R_nonlinear <- RespoR_Normalized_Full_ExcelUpdates_C_R %>%
  nest(data = -c(Predictor_Variable)) %>% # nest all the data measurement type
  mutate(fit = map(data, ~lm(Response_Variable~ poly(Predictor_Values, degree=2), data = .))) #create models
MS_C_R_nonlinear

MS_C_R_nonlinear_fit <- MS_C_R_nonlinear$fit # shows you each of the models

MS_C_R_nonlinear_fitresults <- MS_C_R_nonlinear %>%
  mutate(coeff = map(fit, tidy),
         aic =  map(fit, glance)) %>% # R2 and others
  select(Predictor_Variable, coeff, aic) %>% # only keep the results
  unnest() %>%
  write_csv(here::here("Outputs", "ModelSelection", "C_R.csv"))

## for Cabral NP
MS_C_NP_nonlinear <- RespoR_Normalized_Full_ExcelUpdates_C_NP %>%
  nest(data = -c(Predictor_Variable)) %>% # nest all the data measurement type
  mutate(fit = map(data, ~lm(Response_Variable~ poly(Predictor_Values, degree=2), data = .))) #create models
MS_C_NP_nonlinear

MS_C_NP_nonlinear_fit <- MS_C_NP_nonlinear$fit # shows you each of the models

MS_C_NP_nonlinear_fitresults <- MS_C_NP_nonlinear %>%
  mutate(coeff = map(fit, tidy),
         aic =  map(fit, glance)) %>% # R2 and others
  select(Predictor_Variable, coeff, aic) %>% # only keep the results
  unnest() %>%
  write_csv(here::here("Outputs", "ModelSelection", "C_NP.csv"))


## for Cabral GP
MS_C_GP_nonlinear <- RespoR_Normalized_Full_ExcelUpdates_C_GP %>%
  nest(data = -c(Predictor_Variable)) %>% # nest all the data measurement type
  mutate(fit = map(data, ~lm(Response_Variable~ poly(Predictor_Values, degree=2), data = .))) #create models
MS_C_GP_nonlinear

MS_C_GP_nonlinear_fit <- MS_C_GP_nonlinear$fit # shows you each of the models

MS_C_GP_nonlinear_fitresults <- MS_C_GP_nonlinear %>%
  mutate(coeff = map(fit, tidy),
         aic =  map(fit, glance)) %>% # R2 and others
  select(Predictor_Variable, coeff, aic) %>% # only keep the results
  unnest() %>%
  write_csv(here::here("Outputs", "ModelSelection", "C_GP.csv"))

###########################################################
### clean names and calculating delta AIC for params for each site and physio measurement 
###########################################################

### Cabral GP 
MS_C_GP_nonlinear_fitresults_cleannames <- MS_C_GP_nonlinear_fitresults %>%
  mutate(Predictor = dplyr::recode(Predictor_Variable,
                            "NN_umolL" = "Nitrite + Nitrate",
                            "phosphate_umolL" = "Phosphate",
                            "silicate_umolL" = "Silicate",
                            "ammonia_umolL" = "Ammonia", 
                            "new_pH" = "pH", 
                            "TA_initial" = "Initial TA")) %>%
  mutate(delAIC = AIC - min(AIC)) %>%
  arrange(delAIC)
## result: ammonia is strongest driver

### Cabral NP 
MS_C_NP_nonlinear_fitresults_cleannames <- MS_C_NP_nonlinear_fitresults %>%
  mutate(Predictor = dplyr::recode(Predictor_Variable,
                            "NN_umolL" = "Nitrite + Nitrate",
                            "phosphate_umolL" = "Phosphate",
                            "silicate_umolL" = "Silicate",
                            "ammonia_umolL" = "Ammonia", 
                            "new_pH" = "pH", 
                            "TA_initial" = "Initial TA")) %>%
  mutate(delAIC = AIC - min(AIC)) %>%
  arrange(delAIC)
## result: silicate is strongest driver 

### Cabral R 
MS_C_R_nonlinear_fitresults_cleannames <- MS_C_R_nonlinear_fitresults %>%
  mutate(Predictor = dplyr::recode(Predictor_Variable,
                            "NN_umolL" = "Nitrite + Nitrate",
                            "phosphate_umolL" = "Phosphate",
                            "silicate_umolL" = "Silicate",
                            "ammonia_umolL" = "Ammonia", 
                            "new_pH" = "pH", 
                            "TA_initial" = "Initial TA")) %>%
  mutate(delAIC = AIC - min(AIC)) %>%
  arrange(delAIC)
## result: Ammonia is strongest driver

### Varari R 
MS_V_R_nonlinear_fitresults_cleannames <- MS_V_R_nonlinear_fitresults %>%
  mutate(Predictor = dplyr::recode(Predictor_Variable,
                            "NN_umolL" = "Nitrite + Nitrate",
                            "phosphate_umolL" = "Phosphate",
                            "silicate_umolL" = "Silicate",
                            "ammonia_umolL" = "Ammonia", 
                            "new_pH" = "pH", 
                            "TA_initial" = "Initial TA")) %>%
  mutate(delAIC = AIC - min(AIC)) %>%
  arrange(delAIC)
## result: pH is strongest driver

### Varari NP 
MS_V_NP_nonlinear_fitresults_cleannames <- MS_V_NP_nonlinear_fitresults %>%
  mutate(Predictor = dplyr::recode(Predictor_Variable,
                            "NN_umolL" = "Nitrite + Nitrate",
                            "phosphate_umolL" = "Phosphate",
                            "silicate_umolL" = "Silicate",
                            "ammonia_umolL" = "Ammonia", 
                            "new_pH" = "pH", 
                            "TA_initial" = "Initial TA")) %>%
  mutate(delAIC = AIC - min(AIC)) %>%
  arrange(delAIC)
## result: Silicate is strongest driver 

### Varari GP 
MS_V_GP_nonlinear_fitresults_cleannames <- MS_V_GP_nonlinear_fitresults %>%
  mutate(Predictor = dplyr::recode(Predictor_Variable,
                            "NN_umolL" = "Nitrite + Nitrate",
                            "phosphate_umolL" = "Phosphate",
                            "silicate_umolL" = "Silicate",
                            "ammonia_umolL" = "Ammonia", 
                            "new_pH" = "pH", 
                            "TA_initial" = "Initial TA")) %>%
  mutate(delAIC = AIC - min(AIC)) %>%
  arrange(delAIC)
## result: Salinity is strongest driver 


```


### Tidy df for the NEC measurements from different df 
```{r}

NEC_wnuts_V <- FULL_RespoNEC_allParams %>% 
  filter(site=="Varari", 
         P_R=="C") %>% 
  pivot_longer(cols = phosphate_umolL:Salinity, names_to = "Predictor_Variable", values_to = "Predictor_Values") %>% 
  mutate(Response_Variable=umol.cm2.hr) %>% 
  drop_na(umol.cm2.hr) %>% 
  filter(!is.infinite(umol.cm2.hr)) %>% 
  drop_na(Predictor_Values)

NEC_wnuts_C <- FULL_RespoNEC_allParams %>% 
  filter(site=="Cabral", 
         P_R=="C") %>% 
  pivot_longer(cols = phosphate_umolL:Salinity, names_to = "Predictor_Variable", values_to = "Predictor_Values") %>% 
  mutate(Response_Variable=umol.cm2.hr) %>% 
  drop_na(umol.cm2.hr) %>% 
  filter(!is.infinite(umol.cm2.hr)) %>% 
  drop_na(Predictor_Values)
```

## make linear models for NEC 
```{r}
## for Varari 
MS_V_NEC_linear <- NEC_wnuts_V %>%
  nest(data = -c(Predictor_Variable)) %>% # nest all the data measurement type
   mutate(fit = map(data, ~lm(Response_Variable~ Predictor_Values, data = .)))#create models
MS_V_NEC_linear

MS_V_NEC_linear_fit <- MS_V_NEC_linear$fit # shows you each of the models

MS_V_NEC_linear_fitresults <- MS_V_NEC_linear %>%
  mutate(coeff = map(fit, tidy),
         aic =  map(fit, glance)) %>% # R2 and others
  select(Predictor_Variable, coeff, aic) %>% # only keep the results
  unnest() %>%
  write_csv(here::here("Outputs", "ModelSelection", "V_NEC.csv"))

## for Cabral 
MS_C_NEC_linear <- NEC_wnuts_C %>%
  nest(data = -c(Predictor_Variable)) %>% # nest all the data measurement type
   mutate(fit = map(data, ~lm(Response_Variable~ Predictor_Values, data = .)))#create models
MS_C_NEC_linear

MS_C_NEC_linear_fit <- MS_C_NEC_linear$fit # shows you each of the models

MS_C_NEC_linear_fitresults <- MS_C_NEC_linear %>%
  mutate(coeff = map(fit, tidy),
         aic =  map(fit, glance)) %>% # R2 and others
  select(Predictor_Variable, coeff, aic) %>% # only keep the results
  unnest() %>%
  write_csv(here::here("Outputs", "ModelSelection", "C_NEC.csv"))

###########################################################
### clean names and calculating delta AIC for params for each site and for NEC 
###########################################################

### Cabral NEC
MS_C_NEC_linear_fitresults_cleannames <- MS_C_NEC_linear_fitresults %>%
  mutate(Predictor = dplyr::recode(Predictor_Variable,
                            "NN_umolL" = "Nitrite + Nitrate",
                            "phosphate_umolL" = "Phosphate",
                            "silicate_umolL" = "Silicate",
                            "ammonia_umolL" = "Ammonia", 
                            "salinity" = "Salinity", 
                            "new_pH" = "pH", 
                            "TA_initial" = "Initial TA")) %>%
  mutate(delAIC = AIC - min(AIC)) %>%
  arrange(delAIC)
## result: Phosphate is strongest driver

### Varari NEC
MS_V_NEC_linear_fitresults_cleannames <- MS_V_NEC_linear_fitresults %>%
  mutate(Predictor = dplyr::recode(Predictor_Variable,
                            "NN_umolL" = "Nitrite + Nitrate",
                            "phosphate_umolL" = "Phosphate",
                            "silicate_umolL" = "Silicate",
                            "ammonia_umolL" = "Ammonia", 
                            "salinity" = "Salinity", 
                            "new_pH" = "pH", 
                            "TA_initial" = "Initial TA")) %>%
  mutate(delAIC = AIC - min(AIC)) %>%
  arrange(delAIC)
## result: Silicate is strongest driver
```
