---
title: "Summary of Results"
author: "Hannah Merges"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning=FALSE, 
                      message=FALSE)
```

Created on: June 13th, 2024 
Last Updated on: June 13th, 2024 

## There will be three sections:  

  1. <u>First Chapter</u> - **How do different concentrations of the multivariate parameters of SGD affect the physiology of P. acuta fragments, specifically the respiration, net photosynthesis, gross photosynthesis (net P minus R), and calcification rates?** 
Used dilutions to test if different concentrations of these parameters (phosphorous, nitrates/nitrites, silicate, ammonia, salinity, pH, and TA) had different effects on physiological rates. 

  2. <u>Second Chapter, Part 1</u> - **Does SGD affect the settlement of P. acuta larvae?** Used a controlled lab experiment to test different levels of SGD to see if there was an effect on the amount of larvae that settled 

  3. <u>Second Chapter, Part 2</u> - **Does SGD affect the settlement of Pocillopora larvae?** Used recruitment tiles _in situ_ along a natural gradient to assess if level of SGD (determined by silicate and NN + P) was associated with numbers of settlers on the tiles. 

## First Chapter, Results: 
Tested for multiple different things: 

-  Each individual environmental parameter on the x-axis (Nitrate+Nitrite, Phosphate, Silicate, Ammonia, Salinity, pH, TA, and Temperature)

-  Broad SGD dilutions on the x-axis 

-  GP:R Ratios as a function of each individual environmental parameter

-  GP:R Ratios as a function of SGD

-  Nitrate:Phosphate Ratios as a function of rate (for Respiration, Gross Photosynthesis, and Calcification)

-  GP:NEC Ratio per Site, with GP on the x axis and NEC on the y axis 

#### Each individual environmental parameter on the x-axis (Nitrate+Nitrite, Phosphate, Silicate, Ammonia, Salinity, pH, TA, and Temperature)
-  Cabral GP: Silicate has a significant linear and nonlinear relationship to GP rates and is the lowest AIC in model selection

-  Varari GP: Silicate has a significant nonlinear relationship to GP rates and is the lowest AIC in model selection 

-  Cabral R: Temperature has a significant linear and nonlinear relationship to R rates and is the lowest AIC in model selection.
Nitrate also has a significant linear relationship with R rates 

-  Varari R: pH has a significant linear relationship to R rates and is the lowest AIC in model selection along with silicate (which is 0.06 for nonlinear relationship)

-  Cabral NEC: pH has a significant nonlinear relationship to NEC rates and is the lowest AIC in model selection. 

-  Varari NEC: TA and Silicate **both** have a significant linear and nonlinear relationship to NEC rates and are the lowest AIC in model selection. Phosphate has a significant nonlinear relationship to NEC rates, and salinity has a significant linear relationship. 

Conclusion: The results of analyzing each env. parameter by itself were noisy and did not align with previously published research suggesting that the multidisciplinary nature of SGD cannot be isolated  

#### Broad SGD dilutions on the x-axis 
-  So, we went back to the original analysis which uses the raw groundwater dilutions on the x-axis. Here we see a significant relationship of SGD for: 

-  Cabral GP, linear (0.01549) and nonlinear (0.0155)

-  Varari NEC, linear (0.008) and nonlinear (0.02489) - (if keep the high values), if delete the high values, only nonlinear

#### GP:R Ratios as a function of each individual environmental parameter
-  Varari: Nothing was significant

-  Cabral: Temp is significant (0.004968)

#### GP:R Ratios as a function of SGD
-  Cabral is significant (0.025) but Varari is not 

#### Nitrate:Phosphate Ratios as a function of rate (for Respiration, Gross Photosynthesis, and Calcification)
-  Nothing was significant 

#### GP:NEC Ratio per Site, with GP on the x axis and NEC on the y axis 
-  Neither site was significant 


## Second Chapter, Part 1, Results: 


## Second Chapter, Part 2, Results: 






#### To Do Items: 
- group SGD together by quartiles to get groupings for recruitment tiles 


